export const initialSettings = {
  organizationName: 'Imaan Relief & Development Foundation',
  tagline: 'Restoring Dignity, Building Resilient Communities',
  logo: 'https://lh3.googleusercontent.com/aida/AEtjO1WYIUFqbnG8NPRiRo32mNXeBRT2JS0ixtS30Tq5UaPMngNuQIO0f3uNFXrN9qBsXs1nLzs6nZTpTPu3BpJmsABW2s7Kgtsb2_HEDrvFmS7jFqDVdpmO9CBCpmlKxHB7zjydc19CKTP1iQ35MCs4FGS2aQZXADC4fZpIB2aQ-ZtuE0K0IWe0xFBoT97ExnXdw5XKMHjSmdxa08FFlEwnYywe780AMH_S98IcTkSMN2ml6PBEpy3YLs6Rzw',
  logoDark: '',
  mission: 'To provide principled, immediate emergency humanitarian relief and execute sustainable community-led development programs that restore dignity, nurture self-reliance, and transform vulnerable populations worldwide.',
  vision: 'A resilient world where every community has independent access to clean water, sustainable nourishment, protective education, and economic dignity regardless of race, creed, or geography.',
  description: 'Imaan Relief & Development Foundation is an independent non-profit humanitarian organization dedicated to bridging life-saving frontline relief with durable infrastructure and local capacity building.',
  values: [
    { title: 'Dignity Over Dependency', description: 'Every intervention is co-designed with local community governance to cultivate self-reliance rather than perpetual aid reliance.', icon: 'handshake' },
    { title: '100% Stewardship & Zakat', description: 'Zero administrative deduction policy on designated relief appeals. Every dollar is tracked to field milestone completions.', icon: 'shield_with_heart' },
    { title: 'Radical Transparency', description: 'Independent audited financial accounts, public quarterly mission telemetry, and verified beneficiary documentation.', icon: 'fact_check' },
    { title: 'Humanitarian Neutrality', description: 'Delivering urgent sustenance across disaster and conflict zones unconditionally based strictly on human vulnerability.', icon: 'public' },
  ],
  email: 'info@imanrelief.org',
  phone: '+1 (800) 412-4622',
  emergencyHotline: '+1 (800) 911-3320',
  address: '742 Global Humanitarian Plaza, Suite 400, New York, NY 10017',
  officeHours: 'Monday - Friday: 8:30 AM - 5:30 PM EST',
  charityRegistrationNumber: 'IRDF-883921',
  taxStatus: '501(c)(3) Registered Public Charity • 100% Zakat Compliant',
  socialLinks: {
    facebook: 'https://facebook.com/imaanrelief',
    twitter: 'https://twitter.com/imaanrelief',
    instagram: 'https://instagram.com/imaanrelief',
    linkedin: 'https://linkedin.com/company/imaanrelief',
    youtube: 'https://youtube.com/@imaanrelief',
  },
  impactStatistics: {
    individualsAssisted: '140,000+',
    solarWellsInstalled: '85+',
    activeRegions: '12',
    directProgramRatio: '91%',
    lastAuditedYear: '2024',
  },
  seo: {
    metaTitle: 'Imaan Relief & Development Foundation | Humanitarian Aid & Sustainable Development',
    metaDescription: 'Principled humanitarian emergency relief, solar water boreholes, maternal health, child nutrition, and resilient community development.',
    keywords: ['humanitarian aid', 'water borehole well', 'emergency relief', 'NGO charity', 'zakat donation', 'education continuity'],
    ogImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuArEhRc-Xyvdxiy5v4UyML-yodE_UbwRCmNpO3JGYhMqCQ1Ry3DWbKLkeGghy2M8TdDM0jyxmvsGvz-GAlepfGXpmSv-vedVzI0apAkgPod0BVHbavSknN8At-WYtgcr2OhF7trhKcH_UL7kDG9rUOPU8Xe-6CSvwMhA72pY7TGYQ3s2x3VbfoSqrMAAgTFV6sDUv7P0Rym95QTzJznnKPnMU8r1OfEM9AeEaBp-kyLaYzPhqoPKSrL',
  },
  homepageContent: {
    heroHeadline: 'Restoring Dignity, Building Resilient Communities',
    heroSubheadline: 'Bridging emergency humanitarian relief and long-term sustainable development across vulnerable regions worldwide.',
    criticalAppealTitle: 'East Africa Drought & Food Security Appeal',
    criticalAppealGoal: 600000,
    criticalAppealRaised: 420000,
    stewardshipText: 'We hold every penny in trust. Donors may designate their contribution to our 100% Zakat & Relief Direct Policy, where operational costs are underwritten exclusively by private endowment donors.',
  },
};

export const initialPrograms = [
  {
    title: 'Clean Water & Solar Infrastructure',
    slug: 'clean-water-solar-infrastructure',
    category: 'Water & Sanitation',
    icon: 'water_drop',
    shortDescription: 'Installing community-managed solar water pumping systems and deep boreholes to eliminate water poverty, chronic child dehydration, and waterborne disease.',
    description: 'Our solar water hubs reach depths of up to 180 meters to tap into reliable subterranean aquifers. Powered exclusively by polycrystalline solar arrays, these systems pump uncontaminated water to centralized community distribution kiosks, schools, and health posts.\n\nWater points are protected from surface contamination and tested monthly for biological and chemical potability according to WHO drinking water standards.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC3QyaoK1mScVTcylHhi7TpfXjZo8jFohHo01uAdxIajK7DdC2Vm0W4fzL9589hAZeg1uZp6maLqG0wXjoDgiknnru6blAyHEx7iyzTpwjIV7Q6DW2ofKyXiDud5ud00BRwu4tipBKdrN9EgNBsGI3vQnUX7gRJ49Nuc2hmm6E93OLePPTicjOwf2AMgQyBUNc5EhdU-QE39BI0SmZmSL7wTDbnko-Z9d9A4cLlWXgoI7uUCmbrmP-E',
    objectives: [
      'Eliminate the average 6-kilometer daily trek for clean drinking water',
      'Provide 100% zero-emission solar powered pumping infrastructure',
      'Establish and train democratic Village Water Governance Committees',
      'Drastically reduce diarrheal diseases and child mortality in target regions',
    ],
    targetBeneficiaries: 'Rural pastoralist and farming families lacking municipal water infrastructure',
    locations: ['Turkana, Kenya', 'Shinyanga, Tanzania', 'Kigoma, Tanzania', 'Somaliland', 'Sindh, Pakistan'],
    status: 'active',
    featured: true,
    published: true,
    order: 1,
    stats: [
      { metricValue: '85+', metricLabel: 'Solar Deep Boreholes' },
      { metricValue: '42,000+', metricLabel: 'Daily Beneficiaries' },
      { metricValue: '100%', metricLabel: 'Zero Fossil Fuel Emissions' },
    ],
  },
  {
    title: 'Rapid Emergency Crisis Response',
    slug: 'rapid-emergency-crisis-response',
    category: 'Emergency Relief',
    icon: 'emergency',
    shortDescription: 'Delivering rapid lifesaving relief supplies, insulated shelter kits, emergency surgical units, and clean water tankers during sudden natural disasters and acute conflict crises.',
    description: 'When disasters strike, immediate response within the first 72 hours dictates survival. Imaan Relief maintains pre-positioned logistics warehouses stocked with emergency food survival packs, all-weather insulated family tents, water purification tablets, and trauma surgical supplies.\n\nWorking with vetted local frontline first-responders, relief corridors are activated immediately without bureaucratic delay.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBzrEd-cREPmch8RSwd4vecEo96xxDl4jAKkxlCkhHwRMEuGSx4Nvy4gQ3uF2ozRHgE7PS1WE_Oq7z2YnmlK3Fq0gCSq6KiLQPLI_9haO9YNCBFeQeKxDY3XuNAOPvkhqwbC_MbTOSDjGS4ytj-Q8q3k_D9dV2aesqSmGKqoBS1rRMv-PTNmzd5Ueem4tpXwwObTtCutwVrnmdg0I20uwq0TpUxVq7BKLYavhGXfIsLpPIbkUJ7-ewl',
    objectives: [
      'Rapid field mobilization within 72 hours of sudden-onset emergencies',
      'Distribution of life-sustaining caloric rations and medical supplies',
      'Winterized shelter support for displaced families fleeing conflict',
      'Mobile water purification tankers delivering clean drinking water',
    ],
    targetBeneficiaries: 'Internally displaced persons, disaster survivors, and conflict refugees',
    locations: ['Gaza Strip', 'Horn of Africa', 'Yemen', 'Southern Turkey / Syria Border'],
    status: 'active',
    featured: true,
    published: true,
    order: 2,
    stats: [
      { metricValue: '72hr', metricLabel: 'Average Deployment Speed' },
      { metricValue: '60,000+', metricLabel: 'Emergency Kits Delivered' },
      { metricValue: '4', metricLabel: 'Pre-positioned Regional Corridors' },
    ],
  },
  {
    title: 'Sustainable Livelihood & Agriculture',
    slug: 'sustainable-livelihood-agriculture',
    category: 'Livelihood & Food Security',
    icon: 'agriculture',
    shortDescription: 'Empowering smallholder farmers, women-led micro-enterprises, and youth with climate-smart seeds, micro-grants, drip irrigation systems, and financial literacy.',
    description: 'We believe genuine dignity comes from economic sovereignty. Rather than perpetual food handouts, this initiative equips vulnerable rural families with drip-irrigation infrastructure, drought-resistant heirloom seeds, greenhouse tunnels, and revolving micro-grants.\n\nParticipants form localized agricultural cooperatives, learning value-add processing and collective marketing to sell high-value fresh crops to urban centers.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDIjH1GKIwZVLHTIekUyJqWMQcrf2k-oUieKuSi4Utso01U-lMXGTu0kFGb6xAZX3oK8AzsEkdsPQY_L-TNodIyTdGRd_tro_JNaK2Qm6KFAaX62Z7FBk4vMq292OHKORjvHYQnkIu3b11592GVZLFnOF0_p5dvKa1Rafv6IGXFvMvgTaOSVQyFRMvllRRKfhGg1rpGmppJWv-jv1Qj8SEY1hFHPW8dO3qECQqcAg3Fl3mW5qayO9bi',
    objectives: [
      'Train farmers in regenerative organic cultivation and soil water retention',
      'Provide zero-interest micro-loans to female-headed agribusiness cooperatives',
      'Construct solar-powered micro-irrigation channels to extend growing seasons',
      'Establish direct farm-to-market trade channels without predatory middlemen',
    ],
    targetBeneficiaries: 'Subsistence smallholder farmers, female cooperative heads, and unemployed rural youth',
    locations: ['Niger River Valley', 'Shinyanga, Tanzania', 'Cox’s Bazar, Bangladesh', 'Jordan Valley'],
    status: 'active',
    featured: true,
    published: true,
    order: 3,
    stats: [
      { metricValue: '1,800+', metricLabel: 'Farmers Enrolled' },
      { metricValue: '84%', metricLabel: 'Average Income Increase' },
      { metricValue: '350', metricLabel: 'Hectares Under Drip Irrigation' },
    ],
  },
  {
    title: 'Child Dignity & Education Continuity',
    slug: 'child-dignity-education-continuity',
    category: 'Education Support',
    icon: 'school',
    shortDescription: 'Ensuring displaced and low-income children remain safely in classrooms through learning kits, daily nutritious school feeding programs, teacher stipends, and trauma psychosocial care.',
    description: 'Displacement and extreme poverty shatter educational continuity, putting an entire generation at risk of early exploitation. Our Education Program restores safe, child-friendly learning environments equipped with desks, textbooks, uniform packages, and certified teacher mentorship.\n\nEvery participating student receives a hot, micronutrient-fortified lunch, directly increasing school attendance, cognitive performance, and child retention.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAfhnT5NobOUFrg52tvEMg1lFLgW1jBjGJ5etdGRNOyca7r7eRjiX5QL_TxyYpKi7ovjk7F9gI24k2TQCbimSfSU1q6169uzuj-8BO7zepOLkNUDZx_EGPoyfmMf6s4StZu2MiF6cOVtjaZ7e1SW5WdFG3WW2SfwBtPsORySdtRmR4g2mQLiJPLO2ccNOPuQ9NTzHI51FgwAKEWe4xXFGmrlXB2amkZDc6Y1Zm4lXjUHMXWJizyCOUS',
    objectives: [
      'Maintain continuous schooling during humanitarian displacement crises',
      'Provide comprehensive school uniforms, backpacks, and curriculum materials',
      'Serve daily hot, balanced nutritious meals to eliminate child classroom hunger',
      'Offer certified trauma counseling and psychosocial support for healing',
    ],
    targetBeneficiaries: 'Orphaned children, refugee youth, and vulnerable low-income primary students',
    locations: ['Displaced Camps in Lebanon', 'Northwest Syria', 'Rural Somalia', 'Yemen'],
    status: 'active',
    featured: true,
    published: true,
    order: 4,
    stats: [
      { metricValue: '14', metricLabel: 'Schools Fully Supported' },
      { metricValue: '5,200', metricLabel: 'Active Enrolled Students' },
      { metricValue: '100%', metricLabel: 'Retention & Daily Hot Meals' },
    ],
  },
];

export const initialProjects = [
  {
    title: 'Kigoma Clean Water Solar Borehole #042',
    slug: 'kigoma-clean-water-solar-borehole-042',
    shortDescription: 'Deep 160-meter solar submersible pump installation serving 4,200 villagers in Kigoma Province.',
    description: 'Prior to this project, community members in Kigoma walked over 7 kilometers each morning to collect turbid stream water shared with livestock. Imaan Foundation hydrologists conducted geophysical surveys, drilled to an uncontaminated deep aquifer at 160 meters, and installed high-durability German solar pumping components connected to a 40,000-liter overhead storage tank with 8 distribution taps.',
    location: 'Kigoma Province, Tanzania',
    startDate: '2024-03-10',
    endDate: '2024-11-20',
    status: 'Completed',
    targetBeneficiaries: '4,200 villagers and 2 regional primary schools',
    beneficiariesReached: '4,450 verified community members',
    program: 'clean-water-solar-infrastructure',
    programTitle: 'Clean Water & Solar Infrastructure',
    featured: true,
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuArEhRc-Xyvdxiy5v4UyML-yodE_UbwRCmNpO3JGYhMqCQ1Ry3DWbKLkeGghy2M8TdDM0jyxmvsGvz-GAlepfGXpmSv-vedVzI0apAkgPod0BVHbavSknN8At-WYtgcr2OhF7trhKcH_UL7kDG9rUOPU8Xe-6CSvwMhA72pY7TGYQ3s2x3VbfoSqrMAAgTFV6sDUv7P0Rym95QTzJznnKPnMU8r1OfEM9AeEaBp-kyLaYzPhqoPKSrL',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuArEhRc-Xyvdxiy5v4UyML-yodE_UbwRCmNpO3JGYhMqCQ1Ry3DWbKLkeGghy2M8TdDM0jyxmvsGvz-GAlepfGXpmSv-vedVzI0apAkgPod0BVHbavSknN8At-WYtgcr2OhF7trhKcH_UL7kDG9rUOPU8Xe-6CSvwMhA72pY7TGYQ3s2x3VbfoSqrMAAgTFV6sDUv7P0Rym95QTzJznnKPnMU8r1OfEM9AeEaBp-kyLaYzPhqoPKSrL',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAuCwBOMV7W8CvzhOiKav2BFNETJrqUFAWA3zty8lcyp0gnFSw9TZfLPEMDvyAqE9iUlX73yVuBQYO5-st3mIwgqmse01s9BSWGPWt-ekw-VIgzI5mlIFnr_ytQ1YQSRe-S79MyYHvUQOHuQdP_LBkwl9NWgpgFSrgnGdgnHbwjsYoXlpApzU5FIWM9K4jZcP3wQi1eg6g64g_R3HwDvDNF49P31MPc5s2I1L0SHpd4nIt1Y1Xv6HZt',
    ],
    objectives: [
      'Drill 160m deep borehole to tap clean subterranean aquifer',
      'Mount 12-panel monocrystalline solar array with zero fuel requirement',
      'Construct reinforced concrete tap stands and overflow animal trough',
      'Establish community Water Committee with 50% female representation',
    ],
    activities: [
      'Hydrogeological resistivity testing and community land agreement',
      'Heavy rotary rig drilling, casing installation, and yield flow testing',
      'Installation of solar panels, submersible pump, and water pipeline',
      'Sanitation workshop training for 120 village health volunteers',
    ],
    results: [
      'Borehole successfully commissioned with output of 5,500 liters/hour',
      'Zero reported waterborne cholera or dysentery cases in 9 consecutive months',
      'Primary school attendance increased by 38% for young girls',
    ],
    budgetGoal: 32000,
    fundsRaised: 32000,
    published: true,
  },
  {
    title: 'Emergency Food & Water Relief Blitz',
    slug: 'emergency-food-water-relief-blitz',
    shortDescription: 'Emergency distribution of high-caloric survival food packages and potable water to displaced families.',
    description: 'Providing immediate lifesaving nourishment to families fleeing acute conflict and prolonged drought. Each kit contains fortified wheat flour, lentils, cooking oil, dates, clean water storage jerrycans, and infant nutritional paste.',
    location: 'Horn of Africa Corridors',
    startDate: '2025-01-05',
    endDate: '2025-12-31',
    status: 'Active',
    targetBeneficiaries: '15,000 displaced families',
    beneficiariesReached: '8,420 families reached to date',
    program: 'rapid-emergency-crisis-response',
    programTitle: 'Rapid Emergency Crisis Response',
    featured: true,
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBzrEd-cREPmch8RSwd4vecEo96xxDl4jAKkxlCkhHwRMEuGSx4Nvy4gQ3uF2ozRHgE7PS1WE_Oq7z2YnmlK3Fq0gCSq6KiLQPLI_9haO9YNCBFeQeKxDY3XuNAOPvkhqwbC_MbTOSDjGS4ytj-Q8q3k_D9dV2aesqSmGKqoBS1rRMv-PTNmzd5Ueem4tpXwwObTtCutwVrnmdg0I20uwq0TpUxVq7BKLYavhGXfIsLpPIbkUJ7-ewl',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBzrEd-cREPmch8RSwd4vecEo96xxDl4jAKkxlCkhHwRMEuGSx4Nvy4gQ3uF2ozRHgE7PS1WE_Oq7z2YnmlK3Fq0gCSq6KiLQPLI_9haO9YNCBFeQeKxDY3XuNAOPvkhqwbC_MbTOSDjGS4ytj-Q8q3k_D9dV2aesqSmGKqoBS1rRMv-PTNmzd5Ueem4tpXwwObTtCutwVrnmdg0I20uwq0TpUxVq7BKLYavhGXfIsLpPIbkUJ7-ewl',
    ],
    objectives: [
      'Procure food baskets locally to support regional growers',
      'Distribute emergency relief kits with dignity and biometric verification',
      'Deploy rapid water purification filtration to temporary settlements',
    ],
    activities: [
      'Logistics warehousing in 3 border hubs',
      'Direct convoy delivery with local municipal coordination',
      'Nutritional screening for pregnant mothers and toddlers',
    ],
    results: [
      '8,420 family packages distributed with GPS verification',
      'Over 2.1 million liters of safe drinking water supplied',
    ],
    budgetGoal: 250000,
    fundsRaised: 178500,
    published: true,
  },
  {
    title: 'Women Farmers Solar Drip-Irrigation Initiative',
    slug: 'women-farmers-solar-drip-irrigation',
    shortDescription: 'Equipping 40 women agricultural collective members with gravity drip systems and organic vegetable seeds.',
    description: 'Transforming semi-arid land into flourishing market gardens. Through solar-powered borehole water connections and low-pressure drip pipes, forty female farmers grow drought-resilient crops year-round, securing household food and earning steady cash income.',
    location: 'Shinyanga Region, Tanzania',
    startDate: '2024-06-01',
    endDate: '2025-05-30',
    status: 'Active',
    targetBeneficiaries: '40 women cooperative members & 280 family dependants',
    beneficiariesReached: '40 collective members actively farming',
    program: 'sustainable-livelihood-agriculture',
    programTitle: 'Sustainable Livelihood & Agriculture',
    featured: true,
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC6Z6IyPQx-tWT-4wzylKElNMQxXU8pggC7XwokeNyT5MSxWTOQ6hnKKU5lKWsqE_6fUE-lTCeymLnh543R5hihRQkH7Az8bN8bx-AD4WWq8MnktBIWZDzlFE0fZU3oWHxqwRyWDjr3568dykiJi77hcq3IRi8RinG0CKY36_yWRK9AaROl9JREjbOLwuKJgjhjGwyqrwipM6vWixTfbPGilEovz-2XiB5d0cczT54rrwZM2aDZljuq',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuC6Z6IyPQx-tWT-4wzylKElNMQxXU8pggC7XwokeNyT5MSxWTOQ6hnKKU5lKWsqE_6fUE-lTCeymLnh543R5hihRQkH7Az8bN8bx-AD4WWq8MnktBIWZDzlFE0fZU3oWHxqwRyWDjr3568dykiJi77hcq3IRi8RinG0CKY36_yWRK9AaROl9JREjbOLwuKJgjhjGwyqrwipM6vWixTfbPGilEovz-2XiB5d0cczT54rrwZM2aDZljuq',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDIjH1GKIwZVLHTIekUyJqWMQcrf2k-oUieKuSi4Utso01U-lMXGTu0kFGb6xAZX3oK8AzsEkdsPQY_L-TNodIyTdGRd_tro_JNaK2Qm6KFAaX62Z7FBk4vMq292OHKORjvHYQnkIu3b11592GVZLFnOF0_p5dvKa1Rafv6IGXFvMvgTaOSVQyFRMvllRRKfhGg1rpGmppJWv-jv1Qj8SEY1hFHPW8dO3qECQqcAg3Fl3mW5qayO9bi',
    ],
    objectives: [
      'Install drip irrigation piping across 5 hectares of communal land',
      'Provide training on organic pest management and composting',
      'Open savings and loan cooperative for sustained equipment maintenance',
    ],
    activities: [
      'Land leveling, soil enrichment, and piping installation',
      'Weekly agricultural extension mentorship by certified agronomists',
      'Harvest weighing and local distribution hub linkage',
    ],
    results: [
      'First harvest yielded 14 tonnes of fresh cabbage, peppers, and onions',
      'Household incomes increased by an average of 115%',
    ],
    budgetGoal: 45000,
    fundsRaised: 41200,
    published: true,
  },
];

export const initialStories = [
  {
    title: "Hawa's Village: How Solar Water Transformed Health & Agriculture",
    slug: 'hawas-village-solar-water-transformed-health-agriculture',
    excerpt: 'Before the solar pump was commissioned, Hawa walked six hours each dawn. Today, she leads a thriving 40-member collective cultivating seasonal vegetables and sending daughters to school.',
    content: 'Before dawn broke over the dry savannah, 38-year-old Hawa would begin the daily trek with two 20-liter yellow jerrycans. The nearest riverbed was six kilometers away, and the water scooped from the sandy ditch was brown and muddy.\n\n"My children were sick every month with stomach pains and fever," Hawa recalls. "And because I was walking the entire morning, I could never plant a vegetable garden or earn money."\n\nEverything changed in November when Imaan Relief & Development Foundation commissioned Solar Borehole #042 in her village. Drilled 160 meters down to pure groundwater, the system runs completely on rooftop solar panels.\n\nToday, Hawa fills her containers in three minutes from a shaded tap stand located 200 meters from her home. With her newfound hours, Hawa founded the Ushindi Women’s Cooperative, farming tomatoes, spinach, and sweet peppers under drip lines. Her youngest daughter, Mariam, has not missed a single day of school this semester.\n\n"Clean water gave us back our life and our dignity," she smiles, holding a basket of freshly harvested produce.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC6Z6IyPQx-tWT-4wzylKElNMQxXU8pggC7XwokeNyT5MSxWTOQ6hnKKU5lKWsqE_6fUE-lTCeymLnh543R5hihRQkH7Az8bN8bx-AD4WWq8MnktBIWZDzlFE0fZU3oWHxqwRyWDjr3568dykiJi77hcq3IRi8RinG0CKY36_yWRK9AaROl9JREjbOLwuKJgjhjGwyqrwipM6vWixTfbPGilEovz-2XiB5d0cczT54rrwZM2aDZljuq',
    location: 'Shinyanga Region, Tanzania',
    author: 'Imaan Field Documentary Team',
    readingTime: '4 min read',
    featured: true,
    published: true,
    publishedAt: new Date(),
  },
  {
    title: 'From Survival to School: Amina’s Classroom Dream Realized',
    slug: 'from-survival-to-school-aminas-classroom-dream',
    excerpt: 'How educational continuity kits and daily nutritious meals brought displaced students back into safe learning spaces.',
    content: 'Nine-year-old Amina fled her hometown when regional conflict damaged her community school. For over fourteen months, her education was completely paused while her family lived in emergency transitional shelter.\n\nWhen Imaan Foundation established the Child Dignity Learning Center, Amina was among the first enrolled. Equipped with books, clean uniforms, and hot midday porridge, she has blossomed into one of the top readers in her cohort.\n\n"When I grow up, I want to become a pediatric physician," Amina states with quiet conviction.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAfhnT5NobOUFrg52tvEMg1lFLgW1jBjGJ5etdGRNOyca7r7eRjiX5QL_TxyYpKi7ovjk7F9gI24k2TQCbimSfSU1q6169uzuj-8BO7zepOLkNUDZx_EGPoyfmMf6s4StZu2MiF6cOVtjaZ7e1SW5WdFG3WW2SfwBtPsORySdtRmR4g2mQLiJPLO2ccNOPuQ9NTzHI51FgwAKEWe4xXFGmrlXB2amkZDc6Y1Zm4lXjUHMXWJizyCOUS',
    location: 'Displaced Refugee Corridor, MENA',
    author: 'Tariq Al-Mansoor, Education Lead',
    readingTime: '3 min read',
    featured: false,
    published: true,
    publishedAt: new Date(Date.now() - 7 * 86400000),
  },
];

export const initialNews = [
  {
    title: '2024 Comprehensive Field Audit Released: 91% Direct Program Allocation Confirmed',
    slug: '2024-comprehensive-field-audit-released',
    excerpt: 'Independent institutional auditors verify 100% Zakat execution and over 140,000 individuals supported across 12 field regions.',
    content: 'Imaan Relief & Development Foundation has published its full independent audited financial statements for the fiscal year 2024. The audit confirms that 91.4% of all foundation expenditures were disbursed directly to frontline humanitarian programs and permanent water infrastructure installations.\n\nUnder our 100% Zakat Stewardship covenant, private endowment donors absorb operational administrative overhead, ensuring every penny pledged by community donors reaches frontline relief.',
    featuredImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuArEhRc-Xyvdxiy5v4UyML-yodE_UbwRCmNpO3JGYhMqCQ1Ry3DWbKLkeGghy2M8TdDM0jyxmvsGvz-GAlepfGXpmSv-vedVzI0apAkgPod0BVHbavSknN8At-WYtgcr2OhF7trhKcH_UL7kDG9rUOPU8Xe-6CSvwMhA72pY7TGYQ3s2x3VbfoSqrMAAgTFV6sDUv7P0Rym95QTzJznnKPnMU8r1OfEM9AeEaBp-kyLaYzPhqoPKSrL',
    category: 'Governance & Audits',
    author: 'Board of Trustees & Oversight Committee',
    featured: true,
    published: true,
    publishedAt: new Date(),
  },
  {
    title: 'Emergency Winter Relief Convoy Dispatched to 3,400 Displaced Families',
    slug: 'emergency-winter-relief-convoy-dispatched',
    excerpt: 'Thermal blankets, insulated floor tarpaulins, and three-month family food rations reach vulnerable border encampments.',
    content: 'As sub-zero winter temperatures set in, our rapid deployment logistics teams delivered 3,400 comprehensive winterization kits. Each package contains heavy wool blankets, rainproof shelter insulation, heating fuel vouchers, and high-energy caloric food provisions designed for child nutrition.',
    featuredImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBzrEd-cREPmch8RSwd4vecEo96xxDl4jAKkxlCkhHwRMEuGSx4Nvy4gQ3uF2ozRHgE7PS1WE_Oq7z2YnmlK3Fq0gCSq6KiLQPLI_9haO9YNCBFeQeKxDY3XuNAOPvkhqwbC_MbTOSDjGS4ytj-Q8q3k_D9dV2aesqSmGKqoBS1rRMv-PTNmzd5Ueem4tpXwwObTtCutwVrnmdg0I20uwq0TpUxVq7BKLYavhGXfIsLpPIbkUJ7-ewl',
    category: 'Emergency Update',
    author: 'Emergency Response Taskforce',
    featured: false,
    published: true,
    publishedAt: new Date(Date.now() - 3 * 86400000),
  },
];

export const initialEvents = [
  {
    title: 'Global Water & Climate Resilience Symposium 2025',
    slug: 'global-water-climate-resilience-symposium-2025',
    description: 'An international hybrid briefing bringing together field hydrologists, community elders, and institutional donors to review solar borehole technology and community custody frameworks.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC3QyaoK1mScVTcylHhi7TpfXjZo8jFohHo01uAdxIajK7DdC2Vm0W4fzL9589hAZeg1uZp6maLqG0wXjoDgiknnru6blAyHEx7iyzTpwjIV7Q6DW2ofKyXiDud5ud00BRwu4tipBKdrN9EgNBsGI3vQnUX7gRJ49Nuc2hmm6E93OLePPTicjOwf2AMgQyBUNc5EhdU-QE39BI0SmZmSL7wTDbnko-Z9d9A4cLlWXgoI7uUCmbrmP-E',
    date: '2025-10-18',
    startTime: '10:00 AM EST',
    endTime: '2:30 PM EST',
    location: 'United Nations Plaza & Hybrid Livestream',
    isVirtual: true,
    registrationUrl: 'https://imanrelief.org/events/register/water-symposium',
    status: 'Upcoming',
    published: true,
  },
  {
    title: 'Annual Ramadan & Emergency Relief Banquet',
    slug: 'annual-ramadan-emergency-relief-banquet',
    description: 'Join our leadership, field directors, and compassionate partners for an evening of transparent impact reporting and direct solidarity pledges.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuArEhRc-Xyvdxiy5v4UyML-yodE_UbwRCmNpO3JGYhMqCQ1Ry3DWbKLkeGghy2M8TdDM0jyxmvsGvz-GAlepfGXpmSv-vedVzI0apAkgPod0BVHbavSknN8At-WYtgcr2OhF7trhKcH_UL7kDG9rUOPU8Xe-6CSvwMhA72pY7TGYQ3s2x3VbfoSqrMAAgTFV6sDUv7P0Rym95QTzJznnKPnMU8r1OfEM9AeEaBp-kyLaYzPhqoPKSrL',
    date: '2025-11-12',
    startTime: '6:00 PM EST',
    endTime: '9:30 PM EST',
    location: 'The Grand Ballroom, 450 Lexington Ave, New York',
    isVirtual: false,
    registrationUrl: 'https://imanrelief.org/events/register/annual-banquet',
    status: 'Upcoming',
    published: true,
  },
];

export const initialGallery = [
  {
    title: 'First Flow Celebration at Kigoma Well',
    description: 'Community members celebrate the opening of Solar Borehole #042 with clean drinking water.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuArEhRc-Xyvdxiy5v4UyML-yodE_UbwRCmNpO3JGYhMqCQ1Ry3DWbKLkeGghy2M8TdDM0jyxmvsGvz-GAlepfGXpmSv-vedVzI0apAkgPod0BVHbavSknN8At-WYtgcr2OhF7trhKcH_UL7kDG9rUOPU8Xe-6CSvwMhA72pY7TGYQ3s2x3VbfoSqrMAAgTFV6sDUv7P0Rym95QTzJznnKPnMU8r1OfEM9AeEaBp-kyLaYzPhqoPKSrL',
    category: 'Clean Water',
    location: 'Kigoma, Tanzania',
    year: '2024',
    published: true,
  },
  {
    title: 'Women Cooperative Organic Harvest',
    description: 'Fresh vegetables harvested under drip irrigation in Shinyanga.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC6Z6IyPQx-tWT-4wzylKElNMQxXU8pggC7XwokeNyT5MSxWTOQ6hnKKU5lKWsqE_6fUE-lTCeymLnh543R5hihRQkH7Az8bN8bx-AD4WWq8MnktBIWZDzlFE0fZU3oWHxqwRyWDjr3568dykiJi77hcq3IRi8RinG0CKY36_yWRK9AaROl9JREjbOLwuKJgjhjGwyqrwipM6vWixTfbPGilEovz-2XiB5d0cczT54rrwZM2aDZljuq',
    category: 'Livelihood & Agriculture',
    location: 'Shinyanga, Tanzania',
    year: '2025',
    published: true,
  },
  {
    title: 'Emergency Aid Warehouse Logistics',
    description: 'Field workers preparing nutritional food baskets and emergency medical supplies.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBzrEd-cREPmch8RSwd4vecEo96xxDl4jAKkxlCkhHwRMEuGSx4Nvy4gQ3uF2ozRHgE7PS1WE_Oq7z2YnmlK3Fq0gCSq6KiLQPLI_9haO9YNCBFeQeKxDY3XuNAOPvkhqwbC_MbTOSDjGS4ytj-Q8q3k_D9dV2aesqSmGKqoBS1rRMv-PTNmzd5Ueem4tpXwwObTtCutwVrnmdg0I20uwq0TpUxVq7BKLYavhGXfIsLpPIbkUJ7-ewl',
    category: 'Emergency Relief',
    location: 'Border Logistics Hub',
    year: '2025',
    published: true,
  },
  {
    title: 'Classroom Education Continuity',
    description: 'Students receiving notebooks, textbooks, and daily warm lunch.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAfhnT5NobOUFrg52tvEMg1lFLgW1jBjGJ5etdGRNOyca7r7eRjiX5QL_TxyYpKi7ovjk7F9gI24k2TQCbimSfSU1q6169uzuj-8BO7zepOLkNUDZx_EGPoyfmMf6s4StZu2MiF6cOVtjaZ7e1SW5WdFG3WW2SfwBtPsORySdtRmR4g2mQLiJPLO2ccNOPuQ9NTzHI51FgwAKEWe4xXFGmrlXB2amkZDc6Y1Zm4lXjUHMXWJizyCOUS',
    category: 'Education Support',
    location: 'Displaced Camp School',
    year: '2024',
    published: true,
  },
];

export const initialTeam = [
  {
    name: 'Dr. Zayd Al-Husseini',
    position: 'Executive Director & Co-Founder',
    department: 'Executive Leadership',
    biography: 'Over twenty years leading international disaster logistics and sustainable water engineering initiatives across sub-Saharan Africa and the Middle East.',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    email: 'zayd.husseini@imanrelief.org',
    order: 1,
    published: true,
  },
  {
    name: 'Fatima N. Mwangi',
    position: 'Director of Field Programs & Hydrology',
    department: 'Field Operations',
    biography: 'Senior hydrogeologist specializing in community-maintained solar pumping aquifers and water management governance in arid zones.',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    email: 'fatima.mwangi@imanrelief.org',
    order: 2,
    published: true,
  },
  {
    name: 'Omar E. Kabbara, CPA',
    position: 'Head of Financial Stewardship & Compliance',
    department: 'Financial Governance',
    biography: 'Former international audit partner directing 100% Zakat compliance, fiduciary transparency, and donor assurance.',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    email: 'omar.kabbara@imanrelief.org',
    order: 3,
    published: true,
  },
  {
    name: 'Maryam S. Diallo',
    position: 'Livelihood & Cooperative Development Lead',
    department: 'Community Development',
    biography: 'Specialist in women-led rural agribusiness cooperatives, micro-grant distribution, and regenerative drought agriculture.',
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80',
    email: 'maryam.diallo@imanrelief.org',
    order: 4,
    published: true,
  },
];

export const initialAdmin = {
  name: 'Super Administrator',
  email: 'admin@imanrelief.org',
  password: 'Password123!', // Hashed on save
  role: 'super_admin',
  isActive: true,
};
